export const PRIVILEGES = {
  // User Management
  VIEW_USER: 'VIEW_USER',
  CREATE_USER: 'CREATE_USER',
  MODIFY_USER: 'MODIFY_USER',
  DELETE_USER: 'DELETE_USER',
  LOCK_UNLOCK_USER: 'LOCK_UNLOCK_USER',
  
  // Role Management
  VIEW_ROLE: 'VIEW_ROLE',
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  
  // Test Management
  READ_ONLY: 'READ_ONLY',
  CREATE_TEST_ORDER: 'CREATE_TEST_ORDER',
  MODIFY_TEST_ORDER: 'MODIFY_TEST_ORDER',
  DELETE_TEST_ORDER: 'DELETE_TEST_ORDER',
  REVIEW_TEST_ORDER: 'REVIEW_TEST_ORDER',
  
  // Comments
  ADD_COMMENT: 'ADD_COMMENT',
  MODIFY_COMMENT: 'MODIFY_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  
  // Configuration
  VIEW_CONFIGURATION: 'VIEW_CONFIGURATION',
  CREATE_CONFIGURATION: 'CREATE_CONFIGURATION',
  MODIFY_CONFIGURATION: 'MODIFY_CONFIGURATION',
  DELETE_CONFIGURATION: 'DELETE_CONFIGURATION',
  
  // Monitoring
  VIEW_EVENT_LOGS: 'VIEW_EVENT_LOGS',
  
  // Reagent Management
  ADD_REAGENTS: 'ADD_REAGENTS',
  MODIFY_REAGENTS: 'MODIFY_REAGENTS',
  DELETE_REAGENTS: 'DELETE_REAGENTS',
  
  // Instrument Management
  ADD_INSTRUMENT: 'ADD_INSTRUMENT',
  VIEW_INSTRUMENT: 'VIEW_INSTRUMENT',
  ACTIVATE_DEACTIVATE_INSTRUMENT: 'ACTIVATE_DEACTIVATE_INSTRUMENT',
  EXECUTE_BLOOD_TESTING: 'EXECUTE_BLOOD_TESTING',
} as const;

